### ISSUE TITLE
Problem on encode some cyrylic domain names

### ISSUE THREAD

**Issue by Kazun3500** [kjd/idna#124]
Hi, 

i am trying to encode domain names "надвор’е.бел", "надвор’е.бел" using python, this library, on Linux.

Always receive error - "Codepoint U+2019 at position 7 of 'надвор’е' not allowed". Some internet sites successfully encodes this domain name to punycode.

Can you help me with this problem&

**Comment by sethmlarson** [comment]
The problem is likely that the character `’` works in IDNA 2003, but the new safer standard is IDNA 2008 (the standard this library implements) which forbids most punctuation characters. In order to keep interoperability with old websites (and broken registrars) browsers continue to use IDNA 2003 even if it's not recommended.

**Comment by kjd** [comment]
Yes, punctuation like `’` is expressly disallowed in IDNA. It sounds like the Belarusian ccTLD manager is not doing adequate validation if they are permitting them in registrations.

```
U+2019:
   Name:             RIGHT SINGLE QUOTATION MARK
1  Exceptions:       False
2  Backwards Compat: False
3  Unassigned:       False
4  LDH:              False
   Properties:       Case_Ignorable Grapheme_Base Pattern_Syntax Quotation_Mark
5  .Join Control:    False
   NFKC CF:          U+2019
6  .Unstable:        False
7  .Ignorable Prop:  False
   Block:            General Punctuation
8  .Ignorable Block: False
   Hangul Syll Type: None
9  .Old Hangul Jamo: False
   General Category: Pf
10 .Letters Digits:  False
== IDNA 2008:        DISALLOWED
== UTS 46:           valid  NV8
```

**Comment by Kazun3500** [comment]
thank you. It is completely impossible to solve my problem with this library? Maybe some encoding options? Or you can show me where i must change something in source code for encode this symbol?

**Comment by sethmlarson** [comment]
@Kazun3500 With this library: yes. However, if you know the encoded domain name you want to reach you can use that encoding with whatever library you're passing the domain name to instead of passing unicode characters. ie instead of using `надвор’е.бел` you could use `xn--80aeff0bjo6418c.xn--90ais`.

**Comment by kjd** [comment]
In the very last bullet point of the documentation is a workaround for Emoji, using the same strategy will let you encode/decode this domain. It is part of the same general issue — punctuation/symbols are not allowed in domain names but a very small set of domain registries with lax standards adherence allow them. The big caveat is allowing such domains to work opens you up to a whole category of security attacks which is why they are prohibited in the first place.

**Comment by kjd** [comment]
As a follow up, `надвор’е.бел` is not a registered domain and maybe is not capable of being registered. Perhaps you are trying to solve a non-existent problem? If you are trying to convert an illegal domain that does not exist in the DNS, it is not clear what the use case is.

**Comment by Kazun3500** [comment]
i solved my problem.

1) I was quite wrong about symbol. It is not U+2019, about which i thought. It is U+02BC.
2) I discovered that standard python library as ability to encode strings to punycode and now i use it
3) Use case is simple - i check if domain exists and register it (I am working with one of belorussian registrators). For register domain i need convert domain name to punycode.
4) forbid domains registration with punctuation symbols - good idea, but not it is quite impossible for me.
