### ISSUE TITLE
IDNA package source installation is broken in Poetry - Adhere to PEP-721

### ISSUE THREAD

**Issue by danni-m** [kjd/idna#151]
Poetry follows the new PEP-721 (https://peps.python.org/pep-0721/), forcing source packages to be extracted with "data_filter".

This causes Poetry to fail source distribution installation for IDNA (https://github.com/python-poetry/poetry/issues/8645).

**Comment by kjd** [comment]
It appears the source of this issue is that `idna/tools/intranges.py` is a symlink to `../idna/intranges.py`, which involves backward traversal one level that doesn't escape the source tree. According to PEP-721, "Tools MAY treat them as [invalid], but are NOT REQUIRED to do so". It seems like Poetry treats this as a violation.

Perhaps the `idna-data` can be refactored to not require this symlink, but I don't immediately see a security issue underlying the current composition.

**Comment by kjd** [comment]
Should now be fixed by using another strategy to import without using a backward traversing symlink
