### ISSUE TITLE
Deprecate `setup.cfg`

### ISSUE THREAD

**Issue by kjd** [kjd/idna#155]
`setup.cfg` has been temporarily added to address issue #129, but should be deprecated in favor of the more modern `pyproject.toml`. The current situation duplicates metadata unnecessarily.

**Comment by CAM-Gerlach** [comment]
Revisiting this ≈six months later...

NB, the project currently only has a `setup.cfg`, no `setup.py`, and the build backend is set to Flit in the `pyproject.toml`, so the only way the `setup.cfg` data could ever get consumed is if distros are repackaging IDNA, they manually patch in their own `setup.py`, _and_ that Setuptools is several years out of date and does not support metadata in pyproject.toml, which will otherwise get used instead anyway—and it seems rather unlikely by now that a distro will be using the very latest IDNA, but not Setuptools.

Also, by now they are going to be having the same problem with many, many other core libraries and tools that have switched to either non-Setuptools backends or pyproject metadata with Setuptools, so presumably they have either switched to more modern packaging workflows (as mainstream distros have, AFAIK), or have developed hacks to deal with this.
