### ISSUE TITLE
Patch for CVE-2024-3651, for v3.3

### ISSUE THREAD

**Issue by realsdx** [kjd/idna#179]
Hi @kjd 

Currently I am trying to backport and fix this particular issue on v3.3, I have found this [commit](https://github.com/kjd/idna/commit/5beb28b9dd77912c0dd656d8b0fdba3eb80222e7), which includes the changes but I am having harder time to backport because the `joining_types` dictionary. Could you help me on which portions of the above commit I should apply to v3.3 to fix this security issue?

**Comment by realsdx** [comment]
I have tried to only apply patch for idna/core.py and tools/idna-data and generate `idnadata.py` but that also generates a lot of changes for the file.

**Comment by kjd** [comment]
I think you'll likely need to apply all of it — the change in logic means the `joining_types` data needs to be more expansive in order to mitigate the combinatorial complexity that led to the vulnerability. 

If you need Unicode 14 data (which idna v3.3 provided), you can manually generate that data using the `idnadata` tool included with the source distribution, and using the `--version 14.0.0` argument. That should theoretically result in a smaller delta from the original v3.3 distribution.
