### ISSUE TITLE
Cannot encode u'sande.mÃ¸re-og-romsdal.no'

### ISSUE THREAD

**Issue by jamesyli** [kjd/idna#21]
```
>>> idna.encode(u'sande.mÃ¸re-og-romsdal.no', uts46=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/idna/core.py", line 339, in encode
    s = uts46_remap(s, std3_rules, transitional)
  File "/usr/local/lib/python2.7/dist-packages/idna/core.py", line 331, in uts46_remap
    _unot(code_point), pos + 1, repr(domain)))
idna.core.InvalidCodepoint: Codepoint U+00B8 not allowed at position 9 in u'sande.m\xc3\xb8re-og-romsdal.no'
```

**Comment by jribbens** [comment]
That's correct, \xb8 is indeed not allowed.

If you set std3_rules=True then you will get a step further, in that the \xb8 will be translated as per the IdnaMappingTable into 0020 0327 which then immediately fails because of course 0020=SPACE which is not allowed in domain names, but this obviously makes no sense so maybe something is happening there which I don't understand.

**Comment by kjd** [comment]
This issue here is that your input string is a UTF-8 encoded byte string, not a Unicode string. Therefore it needs to be converted from UTF-8 to Unicode first before running it through IDNA conversion. UTF-8 encodes U+00F8 (o with a slash, ø) as the byte sequence \xc3\xb8. 

>>> '\xc3\xb8'.decode('utf-8')
u'\xf8'
>>> print '\xc3\xb8'.decode('utf-8')
ø

So if we take your string and decode it from UTF-8 first it seems to work as you'd expect:

>>> idna.encode('sande.m\xc3\xb8re-og-romsdal.no'.decode('utf-8'))
'sande.xn--mre-og-romsdal-qqb.no'

And to round-trip it:

>>> idna.decode('sande.xn--mre-og-romsdal-qqb.no')
u'sande.m\xf8re-og-romsdal.no'
>>> print idna.decode('sande.xn--mre-og-romsdal-qqb.no')
sande.møre-og-romsdal.no
>>>

**Comment by jamesyli** [comment]
No, I don't think `sande.xn--mre-og-romsdal-qqb.no` is the correct IDNA2008 conversion of this case. Please refer to http://xn--domain.net/ . There must be something wrong in your code.

**Comment by jribbens** [comment]
You are mistaken.

If `sande.mÃ¸re-og-romsdal.no` really is the domain you are talking about then the library is correct in rejecting it. You can confirm this here: http://unicode.org/cldr/utility/idna.jsp?a=sande.m%C3%83%C2%B8re-og-romsdal.no

If you actually meant the domain `sande.møre-og-romsdal.no` then `sande.xn--mre-og-romsdal-qqb.no` is indeed the correct conversion. You can confirm this here: http://unicode.org/cldr/utility/idna.jsp?a=sande.m%C3%B8re-og-romsdal.no

**Comment by kjd** [comment]
While unlikely, it is of course possible there is a bug. However I think there is not enough information provided to do anything further. If you can provide the exact input and expected output, and make sure you note it in the ticket in a way that can not be corrupted by Github, such as listing out the individual code points or using repr(). If you have other strings to analyze that would also be great.

On its face, "Ã" must be illegal in IDNA as it is a capital letter, which are forbidden in IDNA, so if it was in a domain it would be "ã"; and "¸" must be illegal because it is a combining character with no adjacent character to combine with, plus combining characters are illegal due to IDNA's using of NFKC. So what we know is what is pasted into the topic of this bug is illegal, but that could be simply due to it being corrupted in the process of reporting this bug.

The other datapoint we have is that it is a Norwegian domain, given it ends with ".no". It is likely intended to be in a Norwegian language like Bokmål or Nynorsk. The tilde and cedilla are not used in these languages. The o with a slash is. Given the UTF-8 to Unicode conversion perfectly converts the reported string into something that is legal Norwegian (and appears to map to the name of a Norwegian location — https://en.wikipedia.org/wiki/Møre_og_Romsdal) it is easy to conclude the input string hadn't been converted from UTF-8 encoding to a Unicode string before using the IDNA library.

In sum, I can investigate further but will need more data to work with to do so.

**Comment by kjd** [comment]
In addition, I reviewed xn--domain.net's output and that tool is wrong. It is noting those code points are prohibited at the bottom, but still returning an A-label. However, if you try to use that A-label it is invalid and doesn't decode. Once it hits prohibited/invalid code points in the input string it needs to simply say it is not possible to convert, rather than giving two different half-baked erroneous conversions.

![xn--domain.net Screen Shot](https://cloud.githubusercontent.com/assets/34589/13055324/8bc3d4da-d3c3-11e5-92e1-cfbc9947ca4d.png)
