### ISSUE TITLE
Jython 2.7 cannot deal with the large uts46data structure

### ISSUE THREAD

**Issue by johnabooth** [kjd/idna#28]
Modified core.py, build-uts46data.py, and uts46data.py to support 64kb Java Class limits.
See https://github.com/metavero/idna/pulls

**Comment by kjd** [comment]
Thanks for the patch. Happy to support trying to get this to work with Jython. That said, the patch looks a little kludgy in its approach, I am wondering if we can find a more elegant way to address the problem.

I guess the first question is whether the boundaries of the blocks will need future tweaking or if they leave sufficient headroom for later expansion of the Unicode standard. I assume they were chosen by rough approximation rather than anything scientific.

**Comment by johnabooth** [comment]
Agree it's ugly.  What if I modify to split it out every 1000 members.  Thought on that approach; it should work as the table grows.

**Comment by kjd** [comment]
This should now be fixed in v2.2 published today.
